#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
linter_exit_code=1
all_staged_files=$(git diff --cached --diff-filter=d --name-only)
pnpm run format
linter_exit_code=$?
git add -f $all_staged_files
if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Linter errors have occurred."
  exit 1
else
  echo "${GREEN} ✔ Rome ran without errors."
  exit 0
fi